---
name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: '1.18.0'

      - uses: aquaproj/aqua-installer@a34cc75221784a96e3caf4bbf716ff67a160a3f1 # v1.0.0
        with:
          aqua_version: v1.2.0

      - uses: suzuki-shunsuke/github-action-golangci-lint@21eb516c4e9a92089b8060a2c00326224b33dbfb # v0.1.3
      - name: dry run
        run: bash scripts/test-dry-run.sh

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
        if: startsWith(github.ref, 'refs/tags/')
      - name: fetch tags to release
        run: git fetch --tags
        if: startsWith(github.ref, 'refs/tags/')
      - name: Unshallow
        run: git fetch --prune --unshallow
        if: startsWith(github.ref, 'refs/tags/')

      - name: Generate token
        id: generate_token
        if: startsWith(github.ref, 'refs/tags/')
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
